### ISSUE TITLE
Tracking: Group Chat - Prod (iOS)

### ISSUE THREAD

**Issue by nplasterer** [xmtp/xmtp-ios#284]
### Must have
- [x] Group Consent
- [x] Streaming 
  - [x] #294
  - [x] #295
- [x] Group Chat Names https://github.com/xmtp/libxmtp/issues/548
- [x] Push Notifications https://github.com/xmtp/libxmtp/issues/527
- [x] Who added me in a group https://github.com/xmtp/xmtp-ios/issues/290
- [x] Message send state https://github.com/xmtp/libxmtp/issues/516
- [x] Filter out group message kind https://github.com/xmtp/libxmtp/issues/522
- [x] #296
- [x] Admin roles built on mutable permission scheme https://github.com/orgs/xmtp/projects/11/views/3#
- [x] InboxID Consent

### Nice to have
- [ ] HMACs https://github.com/xmtp/libxmtp/issues/422
- [x] Ability to list current installation Id
- [ ] Ability to `list_my_installations()`
- [ ] Ability to `revoke_installation()`
- [ ] Leave https://github.com/xmtp/libxmtp/issues/441
- [ ] #297
- [ ] Stream Groups (groups and convos) https://github.com/xmtp/libxmtp/issues/504
