### ISSUE TITLE
Tracking: iOS SDK v1.0

### ISSUE THREAD

**Issue by elisealix22** [xmtp/xmtp-ios#7]
### Requirements

Port `xmtp-js` to `xmtp-ios` and demonstrate core functionality in a Swift sample app.

### Developer Preview - [Shipped December 22, 2022]

- [x] Create Swift package: `xmtp_proto`
    - [x] Add a Swift package generator to https://github.com/xmtp/proto   
    - [x] Publish to Swift Package Manager
- [x] Create Swift package: `xmtp-ios`
    - [x] Set up work repo: https://github.com/xmtp/xmtp-ios
    - [x] Add authentication to match xmtp-js
    - [x] Wrap xmtp in a Swift-conventional `xmtp.Client` (like `xmtp-js`)
    - [x] Reproduce utility classes/methods
        - [x] Client
        - [x] ConversationV1
        - [x] ConversationV2
        - [x] Conversations
        - [x] MessageV1
        - [x] MessageV2
        - [x] PrivateKey
        - [x] PublicKey
        - [x] PrivateKeyBundleV1
        - [x] PrivateKeyBundleV2
        - [x] PublicKeyBundle
        - [x] SignedPublicKeyBundle
        - [x] Stream
        - [x] TextCodec
        - [x] CompositeCodec
    - [x] Publish to Swift Package Manager

### GA - [Targeting March 1, 2023]

 - [ ] Integrated with a third party app
    - [ ] Successfully received push notifications
 - [ ] Publish repo README with GA badge
 - [ ] Reference docs for SDK GA: https://github.com/xmtp/xmtp-ios/issues/38

### Nice to haves

- [x] Create sample app: xmtp/example-chat-ios
    - [x] Use xmtp-ios to demonstrate SDK (like `example-chat-react`)
        - [x] Initialize client
        - [x] List messages
        - [x] Send messages
        - [x] Stream messages

### Decision log
- Dec 5, 2022: We are **not** planning on including `conversations.streamAllMessages()` in the Swift SDK for now as we believe between push notifications & periodic polling it will be less useful than it was on web.
- Jan 18, 2023: We are targeting EthDenver for our SDK GA
